---
apiVersion: v1
kind: Service
metadata:
  name: smtp
spec:
  selector:
    app: smtp
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80
  type: LoadBalancer  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: smtp
  template:
    metadata:
      labels:
        app: smtp
    spec:
      containers:
        - name: smtp
          image: rnwood/smtp4dev:latest
