version: '3.3'

services:
  db: # Container de mySQl, aqui foi chamado de DB
    image: mysql:5.7 #FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql #O nome desse volume é db_data e vai ficar em /var/lib/mysql dentro do container
    restart: always
    env_file:
      - ./config/db.env
    networks:
      - backend

  wordpress:
    depends_on:
      - db # Qual container esse que esta sendo criado depende?
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wp.env
    networks:
      - backend

volumes:
  db_data: {}
networks:
  backend:
    driver: bridge